name: vane
version: 0.6.5+3
authors:
- Robert Åkerblom-Andersson <Robert@dartvoid.com>
- Andreas Ölund <Andreas@dartvoid.com>
description: Vane is a class based server side framework.
homepage: http://dartvoid.com/vane/
documentation: http://dartvoid.com/docs/vaneapi/
dependencies:
  http_server: '>=0.9.2+2 <0.10.0'
  logging: '>=0.9.1+1 <0.10.0'
  mongo_dart: '>=0.1.42 <0.2.0'
  uri: '>=0.9.3 <0.10.0'
  yaml: ">=2.0.0 <3.0.0"
  constrain: ">=0.1.4+2 <0.2.0"
  barback: ">=0.15.0 <0.16.0"
  polymer: ">=0.14.0 <0.15.0"
  http: ">=0.11.1+1 <0.12.0"

dev_dependencies:
  unittest: ">=0.11.0+4 <0.12.0"
